// Перечисление всех инструкций (опкодов) нашей виртуальной машины.
// Каждая инструкция займет ровно 1 байт в байт-коде.
export enum Opcode {
  HALT, PUSH_CONST, STORE_VAR, LOAD_VAR, PUSH_TRUE, PUSH_FALSE, POP, PUSH_NULL,
  DUP, PUSH_UNDEFINED, DUP2, PUSH_INT8, CONSOLE_LOG, CONSOLE_WARN, CONSOLE_ERROR,
  ADD, SUB, MUL, DIV, MOD, EXP, EQUAL, NOT_EQUAL, GREATER_THAN, LESS_THAN,
  GREATER_EQUAL, LESS_EQUAL, STRICT_EQUAL, STRICT_NOT_EQUAL, IN, INSTANCEOF,
  NEGATE, NOT, BITWISE_NOT, TYPEOF, VOID, UNARY_PLUS, JUMP_IF_FALSE, JUMP,
  JUMP_IF_TRUE, JUMP_IF_NOT_NULLISH, JUMP_IF_NULLISH_SHORT_CIRCUIT, CALL, RETURN,
  MAKE_CLOSURE, NEW, MAKE_CLASS, DEFINE_METHOD, LOAD_THIS, INVOKE, INVOKE_SPREAD,
  CALL_SPREAD, NEW_SPREAD, MAKE_ARRAY, GET_PROPERTY, SET_PROPERTY, ARRAY_APPEND,
  ARRAY_APPEND_SPREAD, OBJECT_APPEND, OBJECT_APPEND_SPREAD, REST_ARRAY, REST_OBJECT,
  MAKE_OBJECT, LOAD_GLOBAL, TYPEOF_GLOBAL, THROW, SETUP_CATCH, POP_CATCH,
  GET_FOR_IN_ITERATOR, GET_FOR_OF_ITERATOR, ITERATOR_NEXT, LSHIFT, RSHIFT, ZRSHIFT,
  BITWISE_OR, BITWISE_XOR, BITWISE_AND, AWAIT, STORE_GLOBAL, YIELD, DELETE_PROPERTY,
  DELETE_GLOBAL, SUPER_CONSTRUCTOR, INVOKE_SUPER, GET_ASYNC_ITERATOR, ASYNC_ITERATOR_NEXT,
  UNPACK_ITERATOR_RESULT, LOAD_LOCAL, STORE_LOCAL, GET_NAMED_PROPERTY, SET_NAMED_PROPERTY,
}